name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: |
        python -m pip install --upgrade pip setuptools wheel
        # cython is used to build ushuffle.
        python -m pip install --no-cache-dir --upgrade cython
        # We install tensorflow separately because tensorflow installation depends on
        # the environment. The current stable version of tensorflow does not support
        # python 3.9, so we install a specific nightly version.
        python -m pip install --no-cache-dir --editable .[dev] "tf-nightly-cpu==2.5.0.dev20210312"
        python -m pip install --no-cache-dir codecov
    - name: Lint
      run: flake8 cipher
    # TODO: at the moment, the versions of numpy and pandas we install are not typed.
    # Let's wait a bit before checking types here or add a multi-version solution.
    # - name: Check types
    #   run: mypy cipher
    - name: Run tests
      run: pytest cipher
    - name: Get code coverage
      run: codecov
